u"""Limited unittests for Cheshire3."""

__all__ = ['testAll',
           'testBaseStore',
           'testConfigParser',
           'testConfigs',
           'testDocument',
           'testDocumentFactory',
           'testDocumentStore',
           'testDynamic',
           'testExtractor',
           'testNormalizer',
           'testParser',
           'testPreParser',
           'testQueryFactory',
           'testQueryStore',
           'testRecord',
           'testRecordStore',
           'testSession',
           'testTokenizer',
           'testTokenMerger']
